Add packaging info and scripts
pipeseroni/packaging-aur pull request #2
Opened 2018-03-30 13:22 UTC by StefansM

This commit adds some documentation of the packaging process, some git hooks for safety and an autoupdate script for trivial version bumps.

2018-03-30 16:02 UTC, livibetter commented on README.md
> +The entire packaging process can be automated with [scripts/autoupdate], which
You should use [relative link](https://blog.github.com/2013-01-31-relative-links-in-markup-files/), I believe the following would work:

```markdown
... with [scripts/autoupdate](scripts/autoupdate), which
```

2018-03-30 16:02 UTC, livibetter commented on README.md
> +It is recommended that you install [hooks/pre-commit] as a pre-commit hook (`cp
Did you mean `scripts/...` here and in two more occurrences?

2018-03-30 16:02 UTC, livibetter commented on scripts/pre-commit
> +[[ ${#pkgbuild_hashes[@]} == ${#actual_hashes[@]} ]] || hash_mismatch
What is this `hash_mismatch`?  Or is this just intentionally to have a "command not found" ?

Also I think a simple:

```bash
[[ "${pkgbuild_hashes[@]}" == "${actual_hashes[@]}" ]] || hash_mismatch
```

should suffice the comparison without actually checking the length and comparing each hash individually.

2018-03-30 17:05 UTC, StefansM commented
Wow, embarrassing. Yet more proof code reviews are a good thing. Thanks!

Also, at the top of `pre-commit` is an `exit 0`.

I will fix the scripts, test them more thoroughly, and update this PR.

2018-03-31 00:44 UTC, livibetter commented on README.md
> +The entire packaging process can be automated with [scripts/autoupdate], which
You forgot this one.

2018-03-31 00:55 UTC, livibetter requested changes
Also update the Copyright section in README, and require all contribution to be under the same term, you might want to add another Contributing section.

2018-04-07 06:33 UTC, livibetter approved these changes

2018-04-07 06:43 UTC, livibetter commented
@StefansM I'm merging this and the other two, because they were (almost) ready to be merged.  I hope I am not overstepping or interrupt what you still have any commits planned for them.

2018-04-07 06:43 UTC, merged